### ISSUE TITLE
Error in Vector3.LargestAxis()

### ISSUE THREAD

**Issue by edgar005** [Jerdak/KDTree2#1]
Hi
for negative values of Vector3 coordinate values there is an error in Vector3.LargestAxis()

Instead of comparing the values of X,Y,Z, you should compare the absolute values. 

A question: Did you implement all code from scratch? It is very organized, I like it!

**Comment by Jerdak** [comment]
Fixed in d49632f4c861a9ae7ee526c2c91f72d9156db92b, nice catch!  :metal:

That is a subtle issue that doesn't affect accuracy but does impact speed.

Yes the code is all mine, glad you appreciate the organization.
